server:
  servlet:
    context-path: /api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testhgdb  # in-memory 설정
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view : false

search-engine:
  kakao:
    url: https://dapi.kakao.com
    path: /v2/search/blog
    token: e5d890141a40a5289b1d74160b192c81
  naver:
    url: https://openapi.naver.com
    path: /v1/search/blog.json
    clientId: eGc8Dz9wT750GgQGckoE
    clientSecret: bWGdeQJGSG

# 캐시 검색어/검색횟수 데이터 DB 반영 주기
query-cron: "*/1 * * * * *"
