server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testhgdb  # in-memory 설정
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view : false

search-engine:
  kakao:
    url: https://dapi.kakao.com
    path: /v2/search/blog
    token: e5d890141a40a5289b1d74160b192c81
    # todo  네이버 API auth key 발급
  naver:
    url: https://developers.naver.com
    path: /docs/serviceapi/search/blog/blog.md
    id: myId
    password: myPw

# 캐시 검색어/검색횟수 데이터 DB 반영 주기
query-cron: "*/1 * * * * *"
